### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by DimaMishchenko** [htmlprogrammist/EmojiPicker#14]
Experiencing a crash on controller presentation. 
iOS 16.1. 
Seems to be an issued with emojis json. 

<img width="776" alt="Screenshot 2023-02-03 at 10 54 37" src="https://user-images.githubusercontent.com/25247301/216569619-e8a741ff-51c4-44fe-94c0-5a76f9785ac4.png">

**Comment by htmlprogrammist** [comment]
Еhank you for pointing out the problem. Hot fix is on the way. Closed
