### ISSUE TITLE
Isn't this a hard copy from https://github.com/izyumkin/MCEmojiPicker?

### ISSUE THREAD

**Issue by carloshmartins** [htmlprogrammist/EmojiPicker#17]
I know you said it was inspired from https://github.com/izyumkin/MCEmojiPicker, but it looks the same feature in the end.

Why not forking https://github.com/izyumkin/MCEmojiPicker? And contributing to its project. I really don't get it.

This looks like the same repo, but you changed some methods and names and removed the search field.

**Comment by htmlprogrammist** [comment]
It was forked, but he borrowed this idea, as well as many fixes (including what other contributor did) that are here and even README file. When I pointed it out to him, he closed my PR https://github.com/izyumkin/MCEmojiPicker/pull/7 with my updates on his module to become a SPM/CocoaPods module

https://github.com/izyumkin/MCEmojiPicker/commit/ea01387496ff188c9cae9cda47810767fcfdb0b4 (check comments' date and date of closing my PR. Then see changes on Dec 2022). The truth is on my side

**Comment by carloshmartins** [comment]
That's really nice then. Good work.
